### ISSUE TITLE
老哥，试过archlinux吗

### ISSUE THREAD

**Issue by CoinCheung** [KZ25T/wechat-appimage#1]
下载了那个wechat-x86_64.3.AppImage，然后尝试运行，发现有点问题，方便的话麻烦修复一下?
![image](https://github.com/user-attachments/assets/4674cb9f-0bdf-44c1-9807-1e513f8ef028)

**Comment by KZ25T** [comment]
感谢你的反馈。
1. 我没试过 archlinux，我这个灵感就是从archlinux的wechat-bwrap来的。
2. 我今天在外比较忙，如果比较顺利的话明晚上我可以安装一个archlinux试试看。
3. 你这个是怎么得到的报错，上面执行了哪些命令？
4. 我的挂载参数都在 AppRun 里，我那里没有 /etc/alter；你可以试试自行排查（wechat --debug），并且可以试试自己封装（可以使用 wechat --appimage-extract 然后修改里面的 AppRun 文件，之后使用 appimagetool 打包并尝试）。

**Comment by KZ25T** [comment]
都不愿意回复一下，关了
