### ISSUE TITLE
字体可以调大些吗？

### ISSUE THREAD

**Issue by chopin1998** [KZ25T/wechat-appimage#3]
就。。别的都能用，

但是字体有点儿太小了。。。看您说有机会调整字体， 请问有没有详细说明？ 

谢谢！

**Comment by KZ25T** [comment]
这个……我好像没说过能调整字体。

能给出详细信息吗？比如截图（以及和整个屏幕的对比，请注意保护您的隐私）、分辨率、发行版，我可以试试能不能修复。

**Comment by chopin1998** [comment]
> 这个……我好像没说过能调整字体。
> 
> 能给出详细信息吗？比如截图（以及和整个屏幕的对比，请注意保护您的隐私）、分辨率、发行版，我可以试试能不能修复。

README里的  3.1  -> "字体配置文件和（可能有的）显示配置文件。"

我以为是有的。。。


屏幕是 16寸  2560x1600 。。

![IMG_3347](https://github.com/user-attachments/assets/3a74f234-31f5-4b58-ada8-7b4e674944ad)

**Comment by KZ25T** [comment]
这字体算是正常吧，这不是跟右边tg差不多么

那个配置文件是用户配置文件，和软件无关的，目前微信本身似乎没有调整功能。

**Comment by chopin1998** [comment]
> 这字体算是正常吧，这不是跟右边tg差不多么
> 
> 那个配置文件是用户配置文件，和软件无关的，目前微信本身似乎没有调整功能。

公众号里的明显要大一些， 实际chat的窗口里， 得凑近才能看清楚 🤣

如果微信本身没有的话。。。那也没办法了，谢谢！

**Comment by KZ25T** [comment]
这软件也就这样，逆天，咱这 appimage 算是比较好用（可能是最好用）的使用方法了，将就着用吧

**Comment by chopin1998** [comment]
> 这软件也就这样，逆天，咱这 appimage 算是比较好用（可能是最好用）的使用方法了，将就着用吧

是， 我之前是自己chroot 一通魔改， 能用， 但是换个环境就忘记了。。。

感谢！
